language: python
python:
  - "2.7"

notifications:
  email: false

sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/ExampleThrottle
  - PLATFORMIO_CI_SRC=tests/TestConnection
  - PLATFORMIO_CI_SRC=tests/TestMotor

install:
  - pip install -U platformio
  - platformio lib install ArduinoUnit
  - platformio lib install ArduinoJson
  - platformio lib install 883 # Servo
  - platformio lib install https://github.com/Coderlane/arduino-bluetooth/archive/master.zip

script:
  - platformio ci --board=sparkfun_fiov3 --lib="."
