language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/ExampleThrottle

install:
  - pip install -U platformio
  - platformio lib install ArduinoJson
  - platformio lib install https://github.com/Coderlane/arduino-bluetooth/archive/master.zip

script:
  - platformio ci --board=sparkfun_fiov3 --lib="."
